#! /bin/bash

here=$(basename $(pwd))

# TODO: could do better here, e.g. find the root automagically
if [ -f docker-compose.yml ]; then
    root="."
else
    root=".."
fi

export COMPOSE_FILE="docker-compose.yml"
if [ -f docker-compose-custom.yml ]; then
    export COMPOSE_PATH_SEPARATOR=":"
    export COMPOSE_FILE="${COMPOSE_FILE}:${here}/docker-compose-custom.yml"
fi

(
    cd ${root};
    docker-compose "$@"
)
