#! /bin/bash

# Check that we have a reasonable setup
# GitHub Auth

if [[ ! -z "$GITHUB_CLIENT_ID" -a "$RHUB_NO_GITHUB_AUTH" != "true" ]]; then
    >&2 echo "GITHUB_CLIENT_ID is not set"
fi

if [[ ! -z "$GITHUB_CLIENT_SECRET" -a "RHUB_NO_GITHUB_AUTH" != "true" ]]; then
    >&2 echo "GITHUB_CLIENT_SECRET is not set"
fi

# Email setup

if [[ -z "$RHUB_EMAIL_MODE" -o "$RHUB_EMAIL_MODE" == "smtp" ]]; then
    
else

fi

# Check for active Docker Machine

if [[ ! -z "$DOCKER_MACHINE_NAME"  ]]; then
    echo "RHUB> Active Docker Machine: $DOCKER_MACHINE_NAME"
else
    echo "RHUB> No active Docker Machine"
fi

# We are ready to go

if [[ -f stack.yml ]]; then
    echo "RHUB> Setting up base project"

    set -a
    . ./config.env
    set +a

    export COMPOSE_FILE=stack.yml
    export COMPOSE_ARG="-c stack.yml"

else
    echo "RHUB> Setting up $(basename $(pwd)) project"

    set -a
    . ../config.env
    if [[ -f config-custom.env  ]]; then . ./config-custom.env; fi
    set +a

    if [[ ! -f stack-custom.yml ]]; then
	export COMPOSE_FILE="../stack.yml"
	export COMPOSE_ARG="-c ../stack.yml"
    else
	export COMPOSE_PATH_SEPARATOR=":"
	export COMPOSE_FILE="../stack.yml:stack-custom.yml"
	export COMPOSE_ARG="-c ../stack.yml -c stack-custom.yml"
    fi
fi

if [[ "$1" == "docker" && "$2" == "stack" &&  "$3" == "deploy" ]]; then
    shift 3
    echo "RHUB> Calling docker stack deploy $COMPOSE_ARG $@"
    echo
    docker stack deploy $COMPOSE_ARG "$@"
else
    echo "RHUB> Calling $@"
    echo
    "$@"
fi
